# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_by',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='bank_id',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='ifsc',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.AddField(
            model_name='note',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
