# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-23 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0002_auto_20190822_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='priority',
        ),
    ]
