# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-23 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0003_remove_note_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='ifsc',
            new_name='IFSC',
        ),
    ]
