# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-25 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0005_auto_20190824_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='bankData',
        ),
    ]
